### ISSUE TITLE
Please review my SimpleTodo app

### ISSUE THREAD

**Issue by shocron** [shocron/SimpleTodo#1]
@codepathreview
@codepath

**Comment by codepathreview** [comment]
Shahar, can you review the section in the prework about [the readme](http://courses.codepath.com/snippets/intro_to_android/prework#heading-4-submitting-the-project) for your project? In particular, check out this [README template](http://courses.codepath.com/snippets/intro_to_android/readme_templates/prework_readme.md?raw=true) and be sure to [include a GIF recorded with LiceCap](http://www.cockos.com/licecap/). Please ping me back here once that's complete.

**Comment by shocron** [comment]
I'm on it
